"""add users and photo.user_id

Revision ID: 6773f3cb62ab
Revises: 7ab86ef6bdc6
Create Date: 2025-11-28 23:15:51.137430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6773f3cb62ab'
down_revision: Union[str, Sequence[str], None] = '7ab86ef6bdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'user_id')
    # ### end Alembic commands ###
