"""add photo metadata fields

Revision ID: 7ab86ef6bdc6
Revises: 
Create Date: 2025-11-28 22:05:03.136727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab86ef6bdc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('date', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('title', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('caption', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'caption')
    op.drop_column('photos', 'title')
    op.drop_column('photos', 'date')
    op.drop_column('photos', 'upload_time')
    # ### end Alembic commands ###
